easylender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/templates/main/autoacademy/autoacademy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
]


if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/templates/main/autoacademy/main/urls.py
from django.urls import path
from . views import *


urlpatterns =[
    path("", IndexViews.index, name = "index"),
    path("user-login", IndexViews.user_login, name = "user-login"),
    path("user-logout", IndexViews.user_logout, name = "user-logout"),

    #set variables by click
    path("set-current-student-by-click<int:id>",GlobalViewsByClick.set_current_student_by_click, name="set-current-student-by-click"),
    path("set-current-year-class-by-click<int:id>",GlobalViewsByClick.set_current_year_class_by_click, name="set-current-year-class-by-click"),
    path("set-current-year-class-term-by-click<int:id>",GlobalViewsByClick.set_current_year_class_term_by_click, name="set-current-year-class-term-by-click"),
    

    #Bursar urls
    #==================================================================
    path("bursar-dashboard", BursarViews.bursar_dashboard, name="bursar-dashboard"),
    #Student Reuirements
    path("list-requirements", RequirementsViews.list_requirements, name="list-requirements"),

    #search for a student  
    path("search-for-a-student", SearchForStudent.search_for_a_student, name="search-for-a-student"),

    #class lists list-classes
    path("list-classes", classListsView.list_classes, name="list-classes"),

    #student views
    path("add-student", StudentViews.add_student, name="add-student"),
    path("edit-student", StudentViews.edit_student, name="edit-student"),

    #Expemses
    path("expenses", ManageExpense.expenses, name="expenses"),

    #cashbook views
    path("list-cashbook", CashBookViews.list_cashbook, name="list-cashbook"),

    #banking views
    path("list-bank", BankViews.list_bank, name="list-bank"),

    #class settings
    path("list-all-classes", ClassSettings.list_all_classes, name="list-all-classes"),

    ]

main/urls.py
from django.urls import path
from django.contrib.auth.views  import LogoutView
from .views import *


app_name="main"

urlpatterns =[
    #REST FRAMEWORK API USRLS
    path('api-login/', LoginAPIView.login, name='api-login'),
    #user view urls
    path("",index, name="index"),
    path("login/", login_request, name="login"),
    path("native-login/",native_login, name="native-login"),
    path("logout/", LogoutView.as_view(template_name ="user/logout.html"), name="logout"),
    path("change-password/", change_password, name="change-password"),

    #client management views
    path("add-client", ClientView.add_client, name="add-client"),
    path("edit-client", ClientView.edit_client, name="edit-client"),
    path("search-for-a-client", ClientView.search_for_a_client, name="search-for-a-client"),
    path("search-for-a-client/<int:id>", ClientView.set_search_for_a_client, name="set-search-for-a-client"),
    path("set-prev-client", ClientView.set_prev_client, name="set-prev-client"), 
    path("set-next-client", ClientView.set_next_client, name="set-next-client"), 
    path("client-list", ClientView.client_list, name="client-list"),
    #Book adjustments
    path("book-adjustment-report", ClientView.book_adjustment_report, name="book-adjustment-report"),
      
    #Loan management views
    path("add-loan", LoanView.add_loan, name="add-loan"),
    path("edit-loan",  LoanView.edit_loan, name="edit-loan"),
    path("set-prev-loan", LoanView.set_prev_loan, name="set-prev-loan"), 
    path("set-next-loan", LoanView.set_next_loan, name="set-next-loan"),
    path("pay-daily", LoanView.pay_daily, name="pay-daily"), #Daily payments
    path("monthly-loan-payment", LoanView.monthly_loan_payment , name="monthly-loan-payment"),#montlly loan payments
    path("pay-loan", LoanView.pay_loan , name="pay-loan"),#pay_loan
    path("old-loan", LoanView.old_loan, name="old-loan"),#old_loan
    path("edit-loan/<int:id>", LoanView.delete_loan, name="delete-loan"),

    #Images
    path("client-image", Image.client_image, name="client-image"),
    path("national-id", Image.nationaID_image, name="national-id"),
    path("agreement-image", Image.agreement_image, name="agreement-image"),
    path("disburse-iamge", Image.disburse_iamge, name="disburse-iamge"),
    path("security-image", Image.security_image, name="security-image"),
    path("guarantor-image", Image.guarantor_image, name="guarantor-image"),

    #Borrower book management
    path("add-borrower-book", BorrowerBook.add_borrower_book, name="add-borrower-book"),
    path("manually-add-book", BorrowerBook.manually_add_book, name="manually-add-book"),
    

    #Security management views
    path("list-security", SecurityView.list_security, name="list-security"),
    path("add-security", SecurityView.add_security, name="add-security"),
    path("edit-security", SecurityView.edit_security, name="edit-security"),
    path("edit-security/<int:id>", SecurityView.set_security_from_list, name="set-edit-security"),

    #Guarantor management
    path("guarantor-list", GuarantorView.guarantor_list, name="guarantor-list"),
    path("add-guarantor", GuarantorView.add_guarantor, name="add-guarantor"),
    path("edit-guarantor",GuarantorView.edit_guarantor, name="edit-guarantor"),
    path("edit-guarantor/<int:id>",GuarantorView.set_edit_from_list_guarantor, name="set-edit-guarantor"),

    #Loan Reports
    path("approve-loans",  ReportLoans.approve_loans, name="approve-loans"),
    path("approved-loans", ReportLoans.approved_loans, name="approved-loans"),
    path("disbursed-loans", ReportLoans.disbursed_loans, name="disbursed-loans"),
    path("loan-debts", ReportLoans.loan_debts, name="loan-debts"),
    path("visited-loans", ReportLoans.visited_loans, name="visited-loans"),
   
    #Other Incomes and expenses management
    path("manage-incomes-and-expenses", IncomeExpense.manage_incomes_and_expenses, name="manage-incomes-and-expenses"),
    
    #Cashbook 
    path("view-cashbook", CashBookView.view_cashbook, name="view-cashbook"),
    path("view-transactions", CashBookView.view_other_incomes_and_expenses, name="view-transactions"),
    

    #InterestBook 
    path("view-interest-book", InterestBookView.view_interest_book, name="view-interest-book"),

    #Added Interest   added-interest
    path("view-interest", InterestViews.view_interest, name="view-interest"),

    #Added Interest   added-interest
    path("view-interest", InterestViews.view_interest, name="view-interest"),

    #defaulters
    path("view-fines", FinesView.view_fines, name="view-fines"),
    
    #Court Queue
    path("view-court-queue", CourtQueueView.view_court_queue, name="view-court-queue"),
    path("court-transactions", CourtQueueView.court_transactions, name="court-transactions"),
    path("manually-add-court-queue", CourtQueueView.manually_add_court_queue, name="manually-add-court-queue"),
    path("court-details/<int:id>", CourtDetails.set_court_details, name="court-details"),

    
    #Court
    path("view-employees", EmployeeView.view_employees, name="view-employees"),
    path("view-deleted-employees", EmployeeView.view_deleted_employees, name="view-deleted-employees"),
    path("paid-salaries", EmployeeView.paid_salaries, name="paid-salaries"),

    #Pivot reports and Weekly Reports
    path("pivot-reports", PivotTotals.view_report, name="pivot-reports"),
    path("interest-paid-details", WeeklyReportDetailsView.view_interest_paid, name="interest-paid-details"),
    path("view-sold-books", WeeklyReportDetailsView.view_borrowers_book, name="view-sold-books"),
    path("view-processing-fee", WeeklyReportDetailsView.view_processing_fee, name="view-processing-fee"),
    path("detail-view-fines", WeeklyReportDetailsView.view_detail_fines, name="detail-view-fines"),
    path("detail-loan-recovered", WeeklyReportDetailsView.view_detail_loan_recovered, name="detail-loan-recovered"),

    #Stations
    path("view-station", StationsView.view_stations, name="view-stations"),
    path("view-stations-loan-settings", StationsView.stations_loan_seetings, name="view-stations-loan-settings"),
    path("book-settings", StationsView.stations_book_settings, name="book-settings"),
    path("processing-fee-settings", StationsView.stations_processing_fee, name="processing-fee-settings"),
    
    


    ]

main/templates/main/autoacademy/main/views/banking.py
from main.models import CashBook, MoneySource
from django.shortcuts import render, redirect
from django.contrib import messages
from . global_views import GlobalViews
from datetime import datetime, timedelta




GLOBAL_VARIABLES = GlobalViews()
today = datetime.today()
year= today.year
month = today.month
day = today.day
today_date = datetime.strptime(str(year)+"-"+str(month)+"-"+str(day)+ " 00:00:00+03:00","%Y-%m-%d %H:%M:%S%z")
tomorrow_date = today_date + timedelta(days = 1)


class BankViews:
    

    def list_bank(request):

        if request.user.is_authenticated:
            pass
        else:
            return redirect("index")
        
        #get current employee
        current_employee= GLOBAL_VARIABLES.get_current_employee_info(request)
        bank_money_source = MoneySource.objects.get(settings_name = "bank")

        if request.POST.get("bank-amount"):
           bank_actions = BankActions()
           bank_actions.edit_cash_at_bank(request, current_employee, bank_money_source,
            request.POST.get("bank-amount"), request.POST.get("reason"))

        
        opening_balance = 0
        closing_balance = 0
        opening_balance_set = ""
        closing_balance_set = ""

        date1 = today_date
        date2 = tomorrow_date
        
        if not request.POST:
            date1 = today_date
            date2 = tomorrow_date
            orig_date1 = str(today_date).split(" ")[0]
            orig_date2 = str(today_date).split(" ")[0]
        elif request.POST.get("date1") and request.POST.get("date2"): 
            date1 = request.POST.get("date1")
            date2 = GLOBAL_VARIABLES.set_date2(request.POST.get("date2"))
            orig_date1 = str(request.POST.get("date1")).split(" ")[0]
            orig_date2 = str(request.POST.get("date2")).split(" ")[0]
        else:
            date1 = today_date
            date2 = tomorrow_date
            orig_date1 = str(today_date).split(" ")[0]
            orig_date2 = str(today_date).split(" ")[0]



        try:   
            opening_balance = CashBook.objects.filter(
                                                  businessID = current_employee.businessID,
                                                  campusID = current_employee.campusID,
                                                  money_sourceID = bank_money_source,
                                                  record_date__lt = date1,
                                                  ).order_by("-id")[0].running_total
        except:
           opening_balance_set = "Not set"




        try:
            closing_balance = CashBook.objects.filter(
                                                  businessID = current_employee.businessID,
                                                  campusID = current_employee.campusID,
                                                  money_sourceID = bank_money_source,
                                                  record_date__gte = date1,
                                                  record_date__lte = date2,
                                                  ).order_by("-id")[0].running_total
        except:
            closing_balance_set = "Not set"



        bank_list = CashBook.objects.filter(
                                                   businessID = current_employee.businessID,
                                                   campusID = current_employee.campusID,
                                                   money_sourceID = bank_money_source,
                                                   record_date__gte = date1,
                                                   record_date__lte = date2,
                                                    ).order_by("id")
        total_debit=0
        total_credit =0
        net = 0
        count = 0
        for item in bank_list:
            total_debit += item.income_received
            total_credit += item.expense_made
            net += (item.income_received - item.expense_made)
            
            count +=1
    
        return render(
                      request, 
                    template_name ="main/list_bank.html",
                    context={
                        "bank_list":bank_list,
                        "orig_date1":orig_date1,
                        "orig_date2":orig_date2,
                        "total_debit":total_debit,
                        "total_credit":total_credit,
                        "net":net,
                        "count":count,
                        "opening_balance":opening_balance,
                        "closing_balance":closing_balance,
                        "opening_balance_set":opening_balance_set,
                        "closing_balance_set":closing_balance_set,

                    })


class BankActions:
    def edit_cash_at_bank(self, request, current_employee, bank_money_source, amount, reason):
        
        edit_bank = CashBook()
        edit_bank.campusID = current_employee.campusID
        edit_bank.businessID = current_employee.businessID
        edit_bank.running_total = int(amount)
        edit_bank.money_sourceID = bank_money_source
        edit_bank.particulars = "Manually Fix Cash At Bank"
        edit_bank.item_name = reason
        edit_bank.userID = request.user
        edit_bank.user_fullname = str(current_employee.firstname)+" "+str(current_employee.firstname) +" "+str(current_employee.othername)
        edit_bank.save()
        messages.info(request, "Success record saved!")


        

main/templates/main/autoacademy/main/views/class_settings.py
from django.shortcuts import render, redirect
from main . models import Class, StudentType
from . global_views import GlobalViews



GLOBAL_VARIABLES = GlobalViews()
class ClassSettings:

    def list_all_classes(request):
        if request.user.is_authenticated:
            pass
        else:
           return redirect("index")
        
        current_employee = GLOBAL_VARIABLES.get_current_employee_info(request)
        all_classes = Class.objects.filter(
                                           businessID = current_employee.businessID,
                                           campusID = current_employee.campusID,)
        
        ALL_STUDENT_TYPES = StudentType.objects.filter(
                                            campusID =  current_employee.campusID,
                                            businessID= current_employee.businessID,
                                            )

        if request.POST.get("classID"):
            request.session["class_settingsID"] = request.POST.get("classID")
            request.session["student_type_settingsID"] =  request.POST.get("student-typeID")
            return redirect("list-requirements")

        if request.POST.get("student-typeID") and not(request.POST.get("classID")):
            request.session["class_settingsID"] = "NA"
            request.session["student_type_settingsID"] =  request.POST.get("student-typeID")
            return redirect("list-requirements")

        return render(
                    request, 
                    template_name="main/class_settings.html",
                    context = {"all_classes": all_classes,
                    "ALL_STUDENT_TYPES": ALL_STUDENT_TYPES,
                    "no_of_types":ALL_STUDENT_TYPES.__len__(),
                    }
                   )

main/templates/main/autoacademy/main/views/global_views_by_click.py
from django.shortcuts import redirect
from  main.models import Employee, SystemRoles, Rights, CashBook, Student
from datetime import datetime, timedelta

from . global_views import *



GLOBAL_VARIABLES = GlobalViews()

class GlobalViewsByClick:

 
    def set_current_student_by_click(request, id):
        student = Student.objects.get(id = int(id))
        GLOBAL_VARIABLES.set_current_student(request, student)
        return redirect("index") #redirect user to appropriate dashboard using the index_views

    
    def set_current_year_class_by_click(request, id):
        year_class = YearClass.objects.get(id = int(id))
        GLOBAL_VARIABLES.set_current_year_class(request, year_class)
        return redirect("index") #redirect user to appropriate dashboard using the index_views

    def set_current_year_class_term_by_click(request, id):
        year_class_term = YearClassTerm.objects.get(id = int(id))
        GLOBAL_VARIABLES.set_current_year_class_term(request, year_class_term)
        return redirect("index") #redirect user to appropriate dashboard using the index_views

main/templates/pivot_totals.html
{% extends "main/base.html" %}
{% load static %}
{% load humanize %}

{% block content %}

{% if user.is_authenticated %}

<br>
<div class="row">

<br>
<form class="form-inline" method="POST" action="{% url 'main:pivot-reports' %}">
    {% csrf_token %}
    <input type="date" name="date1" placeholder="yyyy-mm-dd" required>&nbsp;
    <input type="date" name="date2" placeholder="yyyy-mm-dd" required>
    <select   name="station-id" id="station">
        <option  value="0">Choose Station</option>
        {% for station in get_global_db_objects.stations %}
            <option value="{{station.id}}">{{station.station_name}}</option>          
        {% endfor %}
    </select>
    <button class="btn btn-sm btn-info text-white" type="submit">Load</button>
    </form>
</div>



<div class="row">

    <h1 class="col-12">Weekly Reports</h1>
    
    {% if request.POST.date1 %}
    <p class="col-12"><b>From:</b> {{request.POST.date1}} <b>To:</b> {{request.POST.date2}} </p>
    {% else %}
    <p class="col-12">Today's Report</p>
    {% endif %}

    <div class="col-12">
        <button class="export-to-excel btn btn-sm btn-info text-white">Export To Excel</button>
        <button class="btn btn-sm btn-success text-white" onclick=" exportToRichText()">Export To Document</button>
    </div>
    <div class="content col-12" id="html-content">
    <table class="table table-striped table-bordered " id="weekly-table" 
    style="border-collapse: collapse; border:1px solid black; width:100%;">
        <thead class="bg-info text-white">
            <tr>
                <td style="border:1px solid gray;">Date</td> <td>Station</td>
                <td style="border:1px solid gray;">Fines</td>
                <td style="border:1px solid gray;">Borrower's Book</td>
                 <td style="border:1px solid gray;">Loan Processing Fee</td> 
                  <td style="border:1px solid gray;">Interest Paid</td> <td>Total</td>
            </tr>
        </thead>

        <tbody>
            {% for item in pivot_weekly %}
            <tr>
                <td style="border:1px solid gray;">{{item.record_date | date:'M d, Y'}}</td> 
                <td style="border:1px solid gray;">{{item.stationID }}</td> 
                <td style="border:1px solid gray;">{{item.fines | floatformat:0 | intcomma }}</td> 
                <td style="border:1px solid gray;">{{item.borrowers_book | floatformat:0 | intcomma }}</td> 
                <td style="border:1px solid gray;">{{item.loan_processing_fee | floatformat:0  | intcomma }}</td> 
                <td style="border:1px solid gray;">{{item.interest_paid | floatformat:0 | intcomma }}</td> 
                <td style="border:1px solid gray;">{{item.total | floatformat:0 | intcomma }}</td> 
            </tr>
            {% endfor %}
        </tbody>
        <tfoot  class="bg-dark text-white">
 
            <tr>
                <td style="border:1px solid gray;"></td>
                <td style="border:1px solid gray;"></td>
                <td style="border:1px solid gray;">{{total_fines | floatformat:0 | intcomma }}</td> 
                <td style="border:1px solid gray;">{{total_on_books | floatformat:0 | intcomma }}</td> 
                <td style="border:1px solid gray;">{{total_processing| floatformat:0 | intcomma  }}</td> 
                <td style="border:1px solid gray;">{{total_interest | floatformat:0 | intcomma  }}</td> 
                <td style="border:1px solid gray;">{{totally | floatformat:0 | intcomma  }}</td> 
            </tr>
        </tfoot>
    </table>
    </div>



  
    {% endif %}

    
    
    <script>
   function exportToRichText() {

    const divElement = document.getElementById("html-content");
    if (!divElement) {
      console.error("Error: Div element with ID '" + divId + "' not found.");
      return;
  }

  const divContent = divElement.outerHTML; // Get the HTML content of the div

  // Create a Blob object with the HTML content and MIME type
  const blob = new Blob([divContent], { type: 'text/html' });

  // Create a downloadable link element (invisible)
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = 'downloaded_div.html'; // Set the filename for the download

  // Simulate a click on the link to trigger download
  link.click();

  // Clean up (optional)
  URL.revokeObjectURL(link.href);
        }

   
        $(".export-to-excel").click(function(){
           $("td").find("input").remove("input")
           $("td").find("label").remove("label")
           $("td").find("i").remove("i")
           $("#weekly-table").table2excel({  
        exclude: "",
        name: "Worksheet",
        filename: "WeeklyReport.xls", // do include extension
        preserveColors: true // set to true if you want background colors and font colors preserved
    })
    
    });
    </script>

    {% endblock %}